### ISSUE TITLE
Is the SDK version old?

### ISSUE THREAD

**Issue by ioridev** [OpenFlutter/Pangolin#18]
I ran the code for "example".

Error occurs when executing _loadRewardAd.

【nativeExpress】两种情况：1. SDK版本低；使用的sdk版本过低，还不支持个性化模板渲染功能。解决办法：升级到平台最新版本sdk。2. 接口使用错误；创建的代码位类型是模板渲染/非模板渲染，但是请求方法是非模板渲染/模板渲染的方法。解决办法：使用模板渲染的方法去请求模板渲染类型或者使用非模板渲染的方法去请求非模板类型的广告，如果代码位在平台上是模板渲染，可以参考文档中个性化模板XX广告的部分，demo中参考带有express部分的代码。如果代码位不是模板渲染，则不要调用含有express字样的接口。参考文档：https://partner.oceanengine.com/doc?id=5dd0fe716b181e00112e3eb8

Is this currently not working?

**Comment by ioridev** [comment]
It's only an ios issue.

**Comment by tongyangsheng** [comment]
Obviously not，I have never defined the SDK version anywhere.
![image](https://user-images.githubusercontent.com/32046282/85486752-d863e480-b5fd-11ea-8eca-9ead09dcd4d5.png)
run pod install in you iOS project, that means you get the latest SDK from CocoaPods.Check the second problem please.Or you can import SDK manually which you can find method on official website.

**Comment by ioridev** [comment]
understood.
It seems to be the second issue because it happens even if you update the SDK version.

I'm running the example code, what is the cause?

**Comment by tongyangsheng** [comment]
There are many situations that can lead to the situation you describe：
1.Check the region to which your network IP belongs. My codeId can only be used in China. If you want to use it in other regions, you need to register one yourself.
2.Please make sure you use a real device for testing instead of the simulator.
